name: Release

permissions:
  contents: write
  actions: write

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_TERM_COLOR: always

  RUST_BACKTRACE: full

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build ${{ matrix.target.name }} package
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          [
            { name: aarch64-apple-darwin, os: macos-latest },
            { name: x86_64-unknown-linux-gnu, os: ubuntu-latest },
            { name: x86_64-pc-windows-msvc, os: windows-latest },
          ]
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v5

      - name: Setup Rust toolchain
        run: rustup target add ${{ matrix.target.name }}

      - name: Build
        run: cargo build --profile ci-release --locked --target ${{ matrix.target.name }}

      - name: Pack (macOS)
        if: matrix.target.os == 'macos-latest'
        run: |
          mv target/${{ matrix.target.name }}/ci-release/x-majordomo .
          zip x-majordomo-${{ matrix.target.name }}.zip x-majordomo

      - name: Pack (Windows)
        if: matrix.target.os == 'windows-latest'
        run: |
          mv target/${{ matrix.target.name }}/ci-release/x-majordomo.exe .
          Compress-Archive -Path x-majordomo.exe -DestinationPath x-majordomo-${{ matrix.target.name }}.zip

      - name: Pack (Linux)
        if: matrix.target.os == 'ubuntu-latest'
        run: |
          mv target/${{ matrix.target.name }}/ci-release/x-majordomo .
          tar -czvf x-majordomo-${{ matrix.target.name }}.tar.gz x-majordomo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x-majordomo-${{ matrix.target.name }}
          path: x-majordomo-${{ matrix.target.name }}.*
          retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5

      - name: Hash
        run: |
          mkdir -p artifacts
          mv x-majordomo-*/* artifacts/
          cd artifacts
          sha256sum * | tee ../SHA256
          md5sum * | tee ../MD5
          mv ../SHA256 .
          mv ../MD5 .

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          discussion_category_name: Announcements
          generate_release_notes: true
          files: artifacts/*
